travis:
  secure:
    BINSTAR_TOKEN: Q59X3yhnw8qsTXTvNLR3IpfJ0fWWJorIvtiJbPU8ML6ViJDLLCuIjgOi77aduEMxz5Y6jaioDpP2eSEEgF5plw8OA0GIUOhfWTUjetTdN7SIFUBczvLwHuiblCU6/aORI0GCpBszBH35VVnrD+E/ZTAz6HXuw4K4bz4cmDamRxEY/YRf5c9mQauMYx3d/v59kmPvqe4evMe4t3HnybnkbkPcmFyEM494X9qg/JHSVubOxme1FVlV4oOaGalXHUUdMZy5cmT8n8qb9yQ1SFijI4baSlI/zqROu0gn2N4SMddB6ennwebiYpGd7CvEYVpRDTM1b6I0a26XIcWCjR7VccNb/fCXXWXbXWIwoXrD6HmgJmCnWmlnTXUEKmuxySDhwlZYRzpK55Pdbcm/Yur6tZ3kiTZEpK7hn0b71OdQmF5T7pfn9xgO0UYCbFY82xxtI2qh2/zylNxpaNBuF9YboOgMsfux/G+8ohNf2SR0jw1YjNv1Xs7AjpuNCKbU3IvHG+F2mkaOMh8yaA/6HFe5aM4L7roP6aU6kxwCCJgLAhFwDJxF/fC3u1pzkogb852TbnFIUn81w6hzAvX+tMu0luv1DRybinl1QtOIIrnmfTXKVw+lpu3CkFwqbVIpv4jU4fLUWi8DE20aZfirDkGgwDMLYNuLFylSPjfKSUPjLNU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
